language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm run lint:script
  - npm run lint:stylesheet
  - npm run type:check:focus
  - npm run test:coverage
  - npm run build
