language: node_js

node_js:
  - 8.9.3

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: 'Tests, Linting, Type checking, and Build'
      # Run unit tests and generate code coverage reports
      name: 'Unit tests'
      script: npm run test:coverage
      if: branch = master
      # Run JavaScript linting
    - name: 'JavaScript linting'
      script: npm run lint:script
      # Run stylesheet linting
    - name: 'Stylesheet linting'
      script: npm run lint:stylesheet
    - # Run static type checking
      name: 'Static type checking'
      script: npm run type:check:focus
      # Create an optimized production build
    - name: 'Production build tests'
      script: npm run build

deploy:
  provider: heroku
  app:
    master: onigiri-webapp
  api_key:
    secure: $HEROKU_API_KEY

after_script:
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN npm run test:coverage:ci
