version: '3.7'

services:
  proxy:
    container_name: $IMAGE_REPO-$SERVICE_PROXY
  app:
    build:
      args:
        BASE_NGINX: $BASE_NGINX
        BUILD_DIR: $DIR_BUILD
        LABEL_AUTHOR_EMAIL: $AUTHOR_EMAIL
        LABEL_AUTHOR_NAME: $AUTHOR_NAME
        LABEL_DESCRIPTION: $IMAGE_DESCRIPTION
        LABEL_LICENSE: $IMAGE_LICENSE
        LABEL_INTERMEDIATE: $IMAGE_INTERMEDIATE
        PORT_EXPOSE: $PORT_PROXY
        PROXY_CONFIG: $PROXY_CONFIG
        PROXY_CONTAINER: $PROXY_CONTAINER
        PROXY_HOST: $PROXY_HOST
        RELEASE_DATE: $RELEASE_DATE
        RELEASE_VERSION: $RELEASE_VERSION
      dockerfile: $DOCKERFILE_PRODUCTION
    environment:
      VIRTUAL_HOST: $DOMAIN_NAME
      VIRTUAL_PORT: $PORT_PROXY
    restart: always
