export const SURVEY_CREATE = 'SurveyNew/SURVEY_CREATE';
export const SURVEY_CREATE_FAILURE = 'SurveyNew/SURVEY_CREATE_FAILURE';
export const SURVEY_CREATE_SUCCESS = 'SurveyNew/SURVEY_CREATE_SUCCESS';

export const SURVEY_RESET_UI = 'SurveyNew/SURVEY_RESET_UI';
