// flow-typed signature: cf283d989bc0620b804753683309e5de
// flow-typed version: <<STUB>>/babel-plugin-jsx-control-statements_v^3.2.8/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-jsx-control-statements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-jsx-control-statements' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-jsx-control-statements/jsx-control-statements.flow' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx-control-statements/jsx-control-statements.latest.flow' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx-control-statements/src/chooseStatement' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx-control-statements/src/forStatement' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx-control-statements/src/ifStatement' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx-control-statements/src/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx-control-statements/src/util/ast' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx-control-statements/src/util/conditional' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx-control-statements/src/util/error' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx-control-statements/src/withStatement' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-jsx-control-statements/jsx-control-statements.flow.js' {
  declare module.exports: $Exports<'babel-plugin-jsx-control-statements/jsx-control-statements.flow'>;
}
declare module 'babel-plugin-jsx-control-statements/jsx-control-statements.latest.flow.js' {
  declare module.exports: $Exports<'babel-plugin-jsx-control-statements/jsx-control-statements.latest.flow'>;
}
declare module 'babel-plugin-jsx-control-statements/src/chooseStatement.js' {
  declare module.exports: $Exports<'babel-plugin-jsx-control-statements/src/chooseStatement'>;
}
declare module 'babel-plugin-jsx-control-statements/src/forStatement.js' {
  declare module.exports: $Exports<'babel-plugin-jsx-control-statements/src/forStatement'>;
}
declare module 'babel-plugin-jsx-control-statements/src/ifStatement.js' {
  declare module.exports: $Exports<'babel-plugin-jsx-control-statements/src/ifStatement'>;
}
declare module 'babel-plugin-jsx-control-statements/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-jsx-control-statements/src/index'>;
}
declare module 'babel-plugin-jsx-control-statements/src/util/ast.js' {
  declare module.exports: $Exports<'babel-plugin-jsx-control-statements/src/util/ast'>;
}
declare module 'babel-plugin-jsx-control-statements/src/util/conditional.js' {
  declare module.exports: $Exports<'babel-plugin-jsx-control-statements/src/util/conditional'>;
}
declare module 'babel-plugin-jsx-control-statements/src/util/error.js' {
  declare module.exports: $Exports<'babel-plugin-jsx-control-statements/src/util/error'>;
}
declare module 'babel-plugin-jsx-control-statements/src/withStatement.js' {
  declare module.exports: $Exports<'babel-plugin-jsx-control-statements/src/withStatement'>;
}
