// flow-typed signature: b9cf9f54b5bddafed5bba31b59983a98
// flow-typed version: <<STUB>>/open-iconic_v^1.1.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'open-iconic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'open-iconic' {
  declare module.exports: any;
}
