// flow-typed signature: 89efec4f37fe4bc6ac9e478a976a9f4f
// flow-typed version: <<STUB>>/prop-types-exact_v^1.1.2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prop-types-exact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prop-types-exact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prop-types-exact/build/helpers/isPlainObject' {
  declare module.exports: any;
}

declare module 'prop-types-exact/build/index' {
  declare module.exports: any;
}

declare module 'prop-types-exact/src/helpers/isPlainObject' {
  declare module.exports: any;
}

declare module 'prop-types-exact/src/index' {
  declare module.exports: any;
}

declare module 'prop-types-exact/test/helpers/_failTestsOnErrors' {
  declare module.exports: any;
}

declare module 'prop-types-exact/test/helpers/callValidator' {
  declare module.exports: any;
}

declare module 'prop-types-exact/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prop-types-exact/build/helpers/isPlainObject.js' {
  declare module.exports: $Exports<'prop-types-exact/build/helpers/isPlainObject'>;
}
declare module 'prop-types-exact/build/index.js' {
  declare module.exports: $Exports<'prop-types-exact/build/index'>;
}
declare module 'prop-types-exact/src/helpers/isPlainObject.js' {
  declare module.exports: $Exports<'prop-types-exact/src/helpers/isPlainObject'>;
}
declare module 'prop-types-exact/src/index.js' {
  declare module.exports: $Exports<'prop-types-exact/src/index'>;
}
declare module 'prop-types-exact/test/helpers/_failTestsOnErrors.js' {
  declare module.exports: $Exports<'prop-types-exact/test/helpers/_failTestsOnErrors'>;
}
declare module 'prop-types-exact/test/helpers/callValidator.js' {
  declare module.exports: $Exports<'prop-types-exact/test/helpers/callValidator'>;
}
declare module 'prop-types-exact/test/index.jsx' {
  declare module.exports: $Exports<'prop-types-exact/test/index'>;
}
