// flow-typed signature: 251b53beb4c387b83861d9128cb26f12
// flow-typed version: <<STUB>>/react-router-last-location_v^1.1.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-last-location'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-last-location' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-last-location/dist/index' {
  declare module.exports: any;
}

declare module 'react-router-last-location/src/index' {
  declare module.exports: any;
}

declare module 'react-router-last-location/src/LastLocationProvider' {
  declare module.exports: any;
}

declare module 'react-router-last-location/src/LastLocationProvider.spec' {
  declare module.exports: any;
}

declare module 'react-router-last-location/src/withLastLocation' {
  declare module.exports: any;
}

declare module 'react-router-last-location/src/withLastLocation.spec' {
  declare module.exports: any;
}

declare module 'react-router-last-location/tests/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-last-location/dist/index.js' {
  declare module.exports: $Exports<'react-router-last-location/dist/index'>;
}
declare module 'react-router-last-location/src/index.js' {
  declare module.exports: $Exports<'react-router-last-location/src/index'>;
}
declare module 'react-router-last-location/src/LastLocationProvider.js' {
  declare module.exports: $Exports<'react-router-last-location/src/LastLocationProvider'>;
}
declare module 'react-router-last-location/src/LastLocationProvider.spec.js' {
  declare module.exports: $Exports<'react-router-last-location/src/LastLocationProvider.spec'>;
}
declare module 'react-router-last-location/src/withLastLocation.js' {
  declare module.exports: $Exports<'react-router-last-location/src/withLastLocation'>;
}
declare module 'react-router-last-location/src/withLastLocation.spec.js' {
  declare module.exports: $Exports<'react-router-last-location/src/withLastLocation.spec'>;
}
declare module 'react-router-last-location/tests/setup.js' {
  declare module.exports: $Exports<'react-router-last-location/tests/setup'>;
}
