// flow-typed signature: 2d26bd22f34e86fe7e0548cfdf3cc32a
// flow-typed version: <<STUB>>/react-sizes_v^1.0.3/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sizes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sizes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sizes/dist/react-sizes' {
  declare module.exports: any;
}

declare module 'react-sizes/dist/react-sizes.min' {
  declare module.exports: any;
}

declare module 'react-sizes/es/contextTypes' {
  declare module.exports: any;
}

declare module 'react-sizes/es/createSizedComponent' {
  declare module.exports: any;
}

declare module 'react-sizes/es/index' {
  declare module.exports: any;
}

declare module 'react-sizes/es/presets' {
  declare module.exports: any;
}

declare module 'react-sizes/es/SizesProvider' {
  declare module.exports: any;
}

declare module 'react-sizes/es/utils/getDisplayName' {
  declare module.exports: any;
}

declare module 'react-sizes/es/utils/getWindowSizes' {
  declare module.exports: any;
}

declare module 'react-sizes/es/utils/shallowDiff' {
  declare module.exports: any;
}

declare module 'react-sizes/es/withSizes' {
  declare module.exports: any;
}

declare module 'react-sizes/lib/contextTypes' {
  declare module.exports: any;
}

declare module 'react-sizes/lib/createSizedComponent' {
  declare module.exports: any;
}

declare module 'react-sizes/lib/index' {
  declare module.exports: any;
}

declare module 'react-sizes/lib/presets' {
  declare module.exports: any;
}

declare module 'react-sizes/lib/SizesProvider' {
  declare module.exports: any;
}

declare module 'react-sizes/lib/utils/getDisplayName' {
  declare module.exports: any;
}

declare module 'react-sizes/lib/utils/getWindowSizes' {
  declare module.exports: any;
}

declare module 'react-sizes/lib/utils/shallowDiff' {
  declare module.exports: any;
}

declare module 'react-sizes/lib/withSizes' {
  declare module.exports: any;
}

declare module 'react-sizes/src/contextTypes' {
  declare module.exports: any;
}

declare module 'react-sizes/src/createSizedComponent' {
  declare module.exports: any;
}

declare module 'react-sizes/src/index' {
  declare module.exports: any;
}

declare module 'react-sizes/src/presets' {
  declare module.exports: any;
}

declare module 'react-sizes/src/SizesProvider' {
  declare module.exports: any;
}

declare module 'react-sizes/src/utils/getDisplayName' {
  declare module.exports: any;
}

declare module 'react-sizes/src/utils/getWindowSizes' {
  declare module.exports: any;
}

declare module 'react-sizes/src/utils/shallowDiff' {
  declare module.exports: any;
}

declare module 'react-sizes/src/withSizes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sizes/dist/react-sizes.js' {
  declare module.exports: $Exports<'react-sizes/dist/react-sizes'>;
}
declare module 'react-sizes/dist/react-sizes.min.js' {
  declare module.exports: $Exports<'react-sizes/dist/react-sizes.min'>;
}
declare module 'react-sizes/es/contextTypes.js' {
  declare module.exports: $Exports<'react-sizes/es/contextTypes'>;
}
declare module 'react-sizes/es/createSizedComponent.js' {
  declare module.exports: $Exports<'react-sizes/es/createSizedComponent'>;
}
declare module 'react-sizes/es/index.js' {
  declare module.exports: $Exports<'react-sizes/es/index'>;
}
declare module 'react-sizes/es/presets.js' {
  declare module.exports: $Exports<'react-sizes/es/presets'>;
}
declare module 'react-sizes/es/SizesProvider.js' {
  declare module.exports: $Exports<'react-sizes/es/SizesProvider'>;
}
declare module 'react-sizes/es/utils/getDisplayName.js' {
  declare module.exports: $Exports<'react-sizes/es/utils/getDisplayName'>;
}
declare module 'react-sizes/es/utils/getWindowSizes.js' {
  declare module.exports: $Exports<'react-sizes/es/utils/getWindowSizes'>;
}
declare module 'react-sizes/es/utils/shallowDiff.js' {
  declare module.exports: $Exports<'react-sizes/es/utils/shallowDiff'>;
}
declare module 'react-sizes/es/withSizes.js' {
  declare module.exports: $Exports<'react-sizes/es/withSizes'>;
}
declare module 'react-sizes/lib/contextTypes.js' {
  declare module.exports: $Exports<'react-sizes/lib/contextTypes'>;
}
declare module 'react-sizes/lib/createSizedComponent.js' {
  declare module.exports: $Exports<'react-sizes/lib/createSizedComponent'>;
}
declare module 'react-sizes/lib/index.js' {
  declare module.exports: $Exports<'react-sizes/lib/index'>;
}
declare module 'react-sizes/lib/presets.js' {
  declare module.exports: $Exports<'react-sizes/lib/presets'>;
}
declare module 'react-sizes/lib/SizesProvider.js' {
  declare module.exports: $Exports<'react-sizes/lib/SizesProvider'>;
}
declare module 'react-sizes/lib/utils/getDisplayName.js' {
  declare module.exports: $Exports<'react-sizes/lib/utils/getDisplayName'>;
}
declare module 'react-sizes/lib/utils/getWindowSizes.js' {
  declare module.exports: $Exports<'react-sizes/lib/utils/getWindowSizes'>;
}
declare module 'react-sizes/lib/utils/shallowDiff.js' {
  declare module.exports: $Exports<'react-sizes/lib/utils/shallowDiff'>;
}
declare module 'react-sizes/lib/withSizes.js' {
  declare module.exports: $Exports<'react-sizes/lib/withSizes'>;
}
declare module 'react-sizes/src/contextTypes.js' {
  declare module.exports: $Exports<'react-sizes/src/contextTypes'>;
}
declare module 'react-sizes/src/createSizedComponent.js' {
  declare module.exports: $Exports<'react-sizes/src/createSizedComponent'>;
}
declare module 'react-sizes/src/index.js' {
  declare module.exports: $Exports<'react-sizes/src/index'>;
}
declare module 'react-sizes/src/presets.js' {
  declare module.exports: $Exports<'react-sizes/src/presets'>;
}
declare module 'react-sizes/src/SizesProvider.js' {
  declare module.exports: $Exports<'react-sizes/src/SizesProvider'>;
}
declare module 'react-sizes/src/utils/getDisplayName.js' {
  declare module.exports: $Exports<'react-sizes/src/utils/getDisplayName'>;
}
declare module 'react-sizes/src/utils/getWindowSizes.js' {
  declare module.exports: $Exports<'react-sizes/src/utils/getWindowSizes'>;
}
declare module 'react-sizes/src/utils/shallowDiff.js' {
  declare module.exports: $Exports<'react-sizes/src/utils/shallowDiff'>;
}
declare module 'react-sizes/src/withSizes.js' {
  declare module.exports: $Exports<'react-sizes/src/withSizes'>;
}
