// flow-typed signature: e2522c20233cc0cfb9b39ace6224a15f
// flow-typed version: <<STUB>>/react-router-scroll-memory_v^1.0.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-scroll-memory'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-scroll-memory' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-scroll-memory/__tests__/getIndexPage.spec' {
  declare module.exports: any;
}

declare module 'react-router-scroll-memory/__tests__/getPage.spec' {
  declare module.exports: any;
}

declare module 'react-router-scroll-memory/__tests__/getScrollPage.spec' {
  declare module.exports: any;
}

declare module 'react-router-scroll-memory/__tests__/saveUrl.spec' {
  declare module.exports: any;
}

declare module 'react-router-scroll-memory/__tests__/scrollTo.spec' {
  declare module.exports: any;
}

declare module 'react-router-scroll-memory/dist/ScrollMemory.min' {
  declare module.exports: any;
}

declare module 'react-router-scroll-memory/exemple/src/About' {
  declare module.exports: any;
}

declare module 'react-router-scroll-memory/exemple/src/App' {
  declare module.exports: any;
}

declare module 'react-router-scroll-memory/exemple/src/Details' {
  declare module.exports: any;
}

declare module 'react-router-scroll-memory/exemple/src/Home' {
  declare module.exports: any;
}

declare module 'react-router-scroll-memory/exemple/src/index' {
  declare module.exports: any;
}

declare module 'react-router-scroll-memory/rollup.config' {
  declare module.exports: any;
}

declare module 'react-router-scroll-memory/src/ScrollMemory' {
  declare module.exports: any;
}

declare module 'react-router-scroll-memory/src/utils/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-scroll-memory/__tests__/getIndexPage.spec.js' {
  declare module.exports: $Exports<'react-router-scroll-memory/__tests__/getIndexPage.spec'>;
}
declare module 'react-router-scroll-memory/__tests__/getPage.spec.js' {
  declare module.exports: $Exports<'react-router-scroll-memory/__tests__/getPage.spec'>;
}
declare module 'react-router-scroll-memory/__tests__/getScrollPage.spec.js' {
  declare module.exports: $Exports<'react-router-scroll-memory/__tests__/getScrollPage.spec'>;
}
declare module 'react-router-scroll-memory/__tests__/saveUrl.spec.js' {
  declare module.exports: $Exports<'react-router-scroll-memory/__tests__/saveUrl.spec'>;
}
declare module 'react-router-scroll-memory/__tests__/scrollTo.spec.js' {
  declare module.exports: $Exports<'react-router-scroll-memory/__tests__/scrollTo.spec'>;
}
declare module 'react-router-scroll-memory/dist/ScrollMemory.min.js' {
  declare module.exports: $Exports<'react-router-scroll-memory/dist/ScrollMemory.min'>;
}
declare module 'react-router-scroll-memory/exemple/src/About.js' {
  declare module.exports: $Exports<'react-router-scroll-memory/exemple/src/About'>;
}
declare module 'react-router-scroll-memory/exemple/src/App.js' {
  declare module.exports: $Exports<'react-router-scroll-memory/exemple/src/App'>;
}
declare module 'react-router-scroll-memory/exemple/src/Details.js' {
  declare module.exports: $Exports<'react-router-scroll-memory/exemple/src/Details'>;
}
declare module 'react-router-scroll-memory/exemple/src/Home.js' {
  declare module.exports: $Exports<'react-router-scroll-memory/exemple/src/Home'>;
}
declare module 'react-router-scroll-memory/exemple/src/index.js' {
  declare module.exports: $Exports<'react-router-scroll-memory/exemple/src/index'>;
}
declare module 'react-router-scroll-memory/index' {
  declare module.exports: $Exports<'react-router-scroll-memory'>;
}
declare module 'react-router-scroll-memory/index.js' {
  declare module.exports: $Exports<'react-router-scroll-memory'>;
}
declare module 'react-router-scroll-memory/rollup.config.js' {
  declare module.exports: $Exports<'react-router-scroll-memory/rollup.config'>;
}
declare module 'react-router-scroll-memory/src/ScrollMemory.js' {
  declare module.exports: $Exports<'react-router-scroll-memory/src/ScrollMemory'>;
}
declare module 'react-router-scroll-memory/src/utils/utils.js' {
  declare module.exports: $Exports<'react-router-scroll-memory/src/utils/utils'>;
}
