// flow-typed signature: 74ddcbd375f8d6d24f9e21d1c82f7e70
// flow-typed version: <<STUB>>/react-google-login_v^3.2.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-google-login'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-google-login' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-google-login/demo/index' {
  declare module.exports: any;
}

declare module 'react-google-login/dist/google-login' {
  declare module.exports: any;
}

declare module 'react-google-login/src/GoogleLogin' {
  declare module.exports: any;
}

declare module 'react-google-login/src/GoogleLogout' {
  declare module.exports: any;
}

declare module 'react-google-login/src/index' {
  declare module.exports: any;
}

declare module 'react-google-login/test/google_logout_test' {
  declare module.exports: any;
}

declare module 'react-google-login/test/google_test' {
  declare module.exports: any;
}

declare module 'react-google-login/test/test_helper' {
  declare module.exports: any;
}

declare module 'react-google-login/webpack/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'react-google-login/webpack/webpack.config.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-google-login/demo/index.js' {
  declare module.exports: $Exports<'react-google-login/demo/index'>;
}
declare module 'react-google-login/dist/google-login.js' {
  declare module.exports: $Exports<'react-google-login/dist/google-login'>;
}
declare module 'react-google-login/src/GoogleLogin.js' {
  declare module.exports: $Exports<'react-google-login/src/GoogleLogin'>;
}
declare module 'react-google-login/src/GoogleLogout.js' {
  declare module.exports: $Exports<'react-google-login/src/GoogleLogout'>;
}
declare module 'react-google-login/src/index.js' {
  declare module.exports: $Exports<'react-google-login/src/index'>;
}
declare module 'react-google-login/test/google_logout_test.js' {
  declare module.exports: $Exports<'react-google-login/test/google_logout_test'>;
}
declare module 'react-google-login/test/google_test.js' {
  declare module.exports: $Exports<'react-google-login/test/google_test'>;
}
declare module 'react-google-login/test/test_helper.js' {
  declare module.exports: $Exports<'react-google-login/test/test_helper'>;
}
declare module 'react-google-login/webpack/webpack.config.dev.js' {
  declare module.exports: $Exports<'react-google-login/webpack/webpack.config.dev'>;
}
declare module 'react-google-login/webpack/webpack.config.prod.js' {
  declare module.exports: $Exports<'react-google-login/webpack/webpack.config.prod'>;
}
