// flow-typed signature: 9439412edf33fc47ff7e7179149166f3
// flow-typed version: <<STUB>>/redux-burger-menu_v^0.2.4/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-burger-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-burger-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-burger-menu/dist/bundle' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/docs/components/Docs' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/docs/index' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/immutable' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/lib/action' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/lib/decorator' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/lib/immutable/action' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/lib/immutable/decorator' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/lib/immutable/index' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/lib/immutable/reducer' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/lib/index' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/lib/reducer' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/server' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/src/action' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/src/decorator' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/src/immutable/action' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/src/immutable/decorator' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/src/immutable/index' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/src/immutable/reducer' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/src/index' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/src/reducer' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/test/action.spec' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/test/decorator.spec' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/test/immutable/action.spec' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/test/immutable/decorator.spec' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/test/immutable/reducer.spec' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/test/reducer.spec' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/test/utils/setup' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/webpack.config' {
  declare module.exports: any;
}

declare module 'redux-burger-menu/webpack.production.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-burger-menu/dist/bundle.js' {
  declare module.exports: $Exports<'redux-burger-menu/dist/bundle'>;
}
declare module 'redux-burger-menu/docs/components/Docs.js' {
  declare module.exports: $Exports<'redux-burger-menu/docs/components/Docs'>;
}
declare module 'redux-burger-menu/docs/index.js' {
  declare module.exports: $Exports<'redux-burger-menu/docs/index'>;
}
declare module 'redux-burger-menu/immutable.js' {
  declare module.exports: $Exports<'redux-burger-menu/immutable'>;
}
declare module 'redux-burger-menu/lib/action.js' {
  declare module.exports: $Exports<'redux-burger-menu/lib/action'>;
}
declare module 'redux-burger-menu/lib/decorator.js' {
  declare module.exports: $Exports<'redux-burger-menu/lib/decorator'>;
}
declare module 'redux-burger-menu/lib/immutable/action.js' {
  declare module.exports: $Exports<'redux-burger-menu/lib/immutable/action'>;
}
declare module 'redux-burger-menu/lib/immutable/decorator.js' {
  declare module.exports: $Exports<'redux-burger-menu/lib/immutable/decorator'>;
}
declare module 'redux-burger-menu/lib/immutable/index.js' {
  declare module.exports: $Exports<'redux-burger-menu/lib/immutable/index'>;
}
declare module 'redux-burger-menu/lib/immutable/reducer.js' {
  declare module.exports: $Exports<'redux-burger-menu/lib/immutable/reducer'>;
}
declare module 'redux-burger-menu/lib/index.js' {
  declare module.exports: $Exports<'redux-burger-menu/lib/index'>;
}
declare module 'redux-burger-menu/lib/reducer.js' {
  declare module.exports: $Exports<'redux-burger-menu/lib/reducer'>;
}
declare module 'redux-burger-menu/server.js' {
  declare module.exports: $Exports<'redux-burger-menu/server'>;
}
declare module 'redux-burger-menu/src/action.js' {
  declare module.exports: $Exports<'redux-burger-menu/src/action'>;
}
declare module 'redux-burger-menu/src/decorator.js' {
  declare module.exports: $Exports<'redux-burger-menu/src/decorator'>;
}
declare module 'redux-burger-menu/src/immutable/action.js' {
  declare module.exports: $Exports<'redux-burger-menu/src/immutable/action'>;
}
declare module 'redux-burger-menu/src/immutable/decorator.js' {
  declare module.exports: $Exports<'redux-burger-menu/src/immutable/decorator'>;
}
declare module 'redux-burger-menu/src/immutable/index.js' {
  declare module.exports: $Exports<'redux-burger-menu/src/immutable/index'>;
}
declare module 'redux-burger-menu/src/immutable/reducer.js' {
  declare module.exports: $Exports<'redux-burger-menu/src/immutable/reducer'>;
}
declare module 'redux-burger-menu/src/index.js' {
  declare module.exports: $Exports<'redux-burger-menu/src/index'>;
}
declare module 'redux-burger-menu/src/reducer.js' {
  declare module.exports: $Exports<'redux-burger-menu/src/reducer'>;
}
declare module 'redux-burger-menu/test/action.spec.js' {
  declare module.exports: $Exports<'redux-burger-menu/test/action.spec'>;
}
declare module 'redux-burger-menu/test/decorator.spec.js' {
  declare module.exports: $Exports<'redux-burger-menu/test/decorator.spec'>;
}
declare module 'redux-burger-menu/test/immutable/action.spec.js' {
  declare module.exports: $Exports<'redux-burger-menu/test/immutable/action.spec'>;
}
declare module 'redux-burger-menu/test/immutable/decorator.spec.js' {
  declare module.exports: $Exports<'redux-burger-menu/test/immutable/decorator.spec'>;
}
declare module 'redux-burger-menu/test/immutable/reducer.spec.js' {
  declare module.exports: $Exports<'redux-burger-menu/test/immutable/reducer.spec'>;
}
declare module 'redux-burger-menu/test/reducer.spec.js' {
  declare module.exports: $Exports<'redux-burger-menu/test/reducer.spec'>;
}
declare module 'redux-burger-menu/test/utils/setup.js' {
  declare module.exports: $Exports<'redux-burger-menu/test/utils/setup'>;
}
declare module 'redux-burger-menu/webpack.config.js' {
  declare module.exports: $Exports<'redux-burger-menu/webpack.config'>;
}
declare module 'redux-burger-menu/webpack.production.config.js' {
  declare module.exports: $Exports<'redux-burger-menu/webpack.production.config'>;
}
