export const SURVEY_DELETE = 'Survey/SURVEY_DELETE';
export const SURVEY_DELETE_FAILURE = 'Survey/SURVEY_DELETE_FAILURE';
export const SURVEY_DELETE_REQUEST = 'Survey/SURVEY_DELETE_REQUEST';
export const SURVEY_DELETE_SUCCESS = 'Survey/SURVEY_DELETE_SUCCESS';

export const SURVEY_REMOVE = 'Survey/SURVEY_REMOVE';

export const SURVEY_SELECTED_ADD = 'Survey/SURVEY_SELECTED_ADD';
export const SURVEY_SELECTED_REMOVE = 'Survey/SURVEY_SELECTED_REMOVE';
